name: qent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.2
  flutter_screenutil: ^5.9.3
  flutter_vector_icons: ^2.0.0
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  im_stepper: ^1.0.1+1
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
